name: Deploy

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Configure Domain
        run: |
          echo "imarker.coderyj.top" > CNAME
          git config --global user.email "sxp_developer@163.com
          git config --global user.name "darkersu"
          git add CNAME
          git commit -m "Configure custom domain"
          git push origin gh-pages